version: '3.8'

services:
  notification-service:
    build: .
    image: gcr.io/spmprojecttest/notification-service:1.0
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - notification_redis
      - notification_db
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=notifications_db

  notification_redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  notification_db:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notifications_db
    ports:
      - "3306:3306"
    volumes:
      - ./src/config/notification.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
