apiVersion: v1
kind: PersistentVolume
metadata:
  name: request-db-pv
  namespace: spmproject
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: request-db-disk
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: request-db-pvc
  namespace: spmproject
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: request-db
  namespace: spmproject
spec:
  replicas: 1
  selector:
    matchLabels:
      app: request-db
  template:
    metadata:
      labels:
        app: request-db
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
            - name: MYSQL_DATABASE
              value: "request"
          volumeMounts:
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d
            - name: csv-files
              mountPath: /var/lib/mysql-files
      volumes:
        - name: init-scripts
          configMap:
            name: request-init-scripts
        - name: csv-files
          persistentVolumeClaim:
            claimName: request-db-pvc
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: request-init-scripts
  namespace: spmproject
data:
  init.sql: |
    -- SQL commands to initialize the database
    LOAD DATA INFILE '/var/lib/mysql-files/request.csv' INTO TABLE request
    FIELDS TERMINATED BY ',' ENCLOSED BY '"'
    LINES TERMINATED BY '\n'
    IGNORE 1 ROWS;