version: "3.8"

services:

  # Simple microservice

  #################################
  # Account: The Account microservice
  #################################
  account:
    build: ./Account
    image: spm/account:1.0
    restart: always
    ports: [ 5001:5000 ]
    depends_on:
      - account_db
    environment:
      DB_HOST: account_db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: account
      DB_PORT: 3306
  #################################
  # Account SQL Database
  #################################
  account_db:
    image: mysql:latest
    restart: always
    ports: [ 3301:3306 ]
    environment:
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_DATABASE: account
    volumes:
      - ./Account/db/account.sql:/docker-entrypoint-initdb.d/init.sql # Mount the file
      - ./Account/employee.csv:/var/lib/mysql-files/employee.csv  # Mount the file
